name: multiplication_trainer
description: "A Flutter application for multiplication table practice and training."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  get_it: ^7.7.0
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5
  dartz: ^0.10.1
  connectivity: ^3.0.6
  shared_preferences: ^2.2.3
  cupertino_icons: ^1.0.6
  confetti: ^0.7.0
  google_fonts: ^6.3.3
  bloc: ^8.1.4
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.4.4
  build_runner: ^2.4.11
  bloc_test: ^9.1.7
  analyzer: ^6.4.1

  flutter_lints: ^4.0.0
  mocktail: ^1.0.4

flutter:



  uses-material-design: true

  generate: true
